# Generated by Codex on 2026-01-17

from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.utils import timezone


def create_sample_data(apps, schema_editor):
    Category = apps.get_model("posts", "Category")
    Topic = apps.get_model("posts", "Topic")
    Post = apps.get_model("posts", "Post")
    User = apps.get_model("auth", "User")

    user, _ = User.objects.get_or_create(
        username="anna.kowalska",
        defaults={
            "email": "anna.kowalska@example.com",
            "first_name": "Anna",
            "last_name": "Kowalska",
            "is_staff": True,
            "is_superuser": True,
        },
    )
    user.password = make_password("tea")
    user.save(update_fields=["password"])

    categories = {}
    for name in ["Herbaty klasyczne", "Ziola lecznicze", "Mieszanki funkcjonalne"]:
        categories[name], _ = Category.objects.get_or_create(name=name)

    topics = {}
    topic_specs = [
        ("Zielona herbata i skupienie", categories["Herbaty klasyczne"]),
        ("Napar z melisy i spokojny sen", categories["Ziola lecznicze"]),
        ("Imbir, kurkuma i odpornosc", categories["Mieszanki funkcjonalne"]),
    ]
    for name, category in topic_specs:
        topics[name], _ = Topic.objects.get_or_create(
            name=name,
            category=category,
            defaults={"created": timezone.now()},
        )

    post_specs = [
        (
            "Zielona herbata na start dnia",
            "zielona-herbata-na-start-dnia",
            topics["Zielona herbata i skupienie"],
            "Delikatny napar z zielonej herbaty wspiera koncentracje i lagodnie pobudza. "
            "Wybieram senche lub lung ching, parze w 75-80°C przez 2-3 minuty. "
            "Po kilku tygodniach takiego rytualu latwiej utrzymac uwage podczas pracy.",
        ),
        (
            "Melisa wieczorem",
            "melisa-wieczorem",
            topics["Napar z melisy i spokojny sen"],
            "Melisa pomaga wyciszyc sie po calym dniu i sprzyja spokojniejszemu snu. "
            "Zalewam lyzeczke suszu szklanka wody i parze 8 minut pod przykryciem. "
            "Dziala najlepiej, gdy ogranicze swiatlo i odloze telefon przed snem.",
        ),
        (
            "Rozgrzewajaca mieszanka z imbirem",
            "rozgrzewajaca-mieszanka-z-imbirem",
            topics["Imbir, kurkuma i odpornosc"],
            "Imbir i kurkuma tworza rozgrzewajacy napar, idealny na chlodniejsze dni. "
            "Dodaje plaster cytryny, odrobine miodu oraz szczypta pieprzu dla lepszego wchlaniania. "
            "Taki napar pije po spacerze lub gdy czuje pierwsze oznaki przeziebienia.",
        ),
    ]

    for title, slug, topic, text in post_specs:
        Post.objects.get_or_create(
            slug=slug,
            defaults={
                "title": title,
                "text": text,
                "topic": topic,
                "created_by": user,
                "created_at": timezone.now(),
                "updated_at": timezone.now(),
            },
        )


def remove_sample_data(apps, schema_editor):
    Category = apps.get_model("posts", "Category")
    Topic = apps.get_model("posts", "Topic")
    Post = apps.get_model("posts", "Post")
    User = apps.get_model("auth", "User")

    Post.objects.filter(
        slug__in=[
            "zielona-herbata-na-start-dnia",
            "melisa-wieczorem",
            "rozgrzewajaca-mieszanka-z-imbirem",
        ]
    ).delete()
    Topic.objects.filter(
        name__in=[
            "Zielona herbata i skupienie",
            "Napar z melisy i spokojny sen",
            "Imbir, kurkuma i odpornosc",
        ]
    ).delete()
    Category.objects.filter(
        name__in=["Herbaty klasyczne", "Ziola lecznicze", "Mieszanki funkcjonalne"]
    ).delete()
    User.objects.filter(username="anna.kowalska").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_topic_created"),
    ]

    operations = [
        migrations.RunPython(create_sample_data, remove_sample_data),
    ]
